# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
        name: install dependencies
        comand: yarn install

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
        name: install dependencies
        command: yarn install
      - run:
        name: test1
        command: yarn test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test